import type { Beach } from "./types";

export const BATHING_WINDOW={startHour:9,endHour:20} as const;
const comparable=(value:string)=>Date.parse(`${value.slice(0,16)}:00Z`);
export function localDateAndHour(now:Date){const formatter=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Madrid",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",hourCycle:"h23"});const parts=formatter.formatToParts(now);const part=(type:Intl.DateTimeFormatPartTypes)=>parts.find(item=>item.type===type)?.value??"00";return{date:`${part("year")}-${part("month")}-${part("day")}`,hour:Number(part("hour"))}}
const isBathingHour=(hour:number)=>hour>=BATHING_WINDOW.startHour&&hour<=BATHING_WINDOW.endHour;
export type TimeOption={time:string;label:string;shortLabel:string};
export function getTodayTimeOptions(beaches:Beach[],now=new Date()):TimeOption[]{const{date,hour}=localDateAndHour(now);const available=[...new Set(beaches.flatMap(beach=>beach.hourlyConditions?.map(item=>item.time.slice(0,16))??[]).filter(time=>time.startsWith(date)&&isBathingHour(Number(time.slice(11,13)))))].sort();return[0,2,4,6].map((offset,index)=>{const targetHour=hour+offset;if(!isBathingHour(targetHour))return undefined;const target=`${date}T${String(targetHour).padStart(2,"0")}:00`;const time=available.reduce<string|undefined>((best,item)=>!best||Math.abs(comparable(item)-comparable(target))<Math.abs(comparable(best)-comparable(target))?item:best,undefined);return time?{time,label:index===0?"Ahora":`+${offset} h`,shortLabel:`${time.slice(11,16)} h`}:undefined}).filter((item):item is TimeOption=>Boolean(item)).filter((item,index,list)=>list.findIndex(other=>other.time===item.time)===index)}
export function selectForecastDate(times:string[],now=new Date()){const localDate=localDateAndHour(now).date;return times.some(time=>time.startsWith(localDate))?localDate:times[0]?.slice(0,10)}
