import type { Beach,BeachHourlyConditions,MetricKey } from "./types";
import { calculateBeachScore,getBeachExclusion } from "./scoring";

const HOURLY_KEYS=( ["waterTemperature","airTemperature","windSpeed","windGust","windDirection","rainProbability","waveHeight","waveDirection","wavePeriod","swellWaveHeight","swellWaveDirection","swellWavePeriod","oceanCurrentVelocity","oceanCurrentDirection"] as const) satisfies readonly (keyof BeachHourlyConditions)[];
const WEATHER_KEYS=new Set<MetricKey>(["airTemperature","windSpeed","windGust","rainProbability"]);

const comparable=(value:string)=>Date.parse(`${value.slice(0,16)}:00Z`);
export function closestHourlyCondition(beach:Beach,targetTime:string){return beach.hourlyConditions?.reduce<BeachHourlyConditions|undefined>((best,item)=>!best||Math.abs(comparable(item.time)-comparable(targetTime))<Math.abs(comparable(best.time)-comparable(targetTime))?item:best,undefined)}

export function beachAtTime(beach:Beach,targetTime?:string):Beach{if(!targetTime)return beach;const point=closestHourlyCondition(beach,targetTime);if(!point)return beach;const projected={...beach,metricMetadata:{...beach.metricMetadata}};for(const key of HOURLY_KEYS){const value=point[key];if(value!==undefined)(projected as unknown as Record<string,unknown>)[key]=value}for(const key of Object.keys(projected.metricMetadata??{}) as MetricKey[]){if(key==="sanitaryStatus"||key==="jellyfishRisk"||key==="occupancy")continue;projected.metricMetadata![key]={...projected.metricMetadata![key]!,validFor:point.time,source:WEATHER_KEYS.has(key)?beach.sources?.weather?.source:beach.sources?.sea?.source}}return projected}

export type TimeOption={time:string;label:string;shortLabel:string};
export function getTodayTimeOptions(beaches:Beach[],now=new Date()):TimeOption[]{const formatter=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Madrid",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",hourCycle:"h23"});const parts=formatter.formatToParts(now);const part=(type:Intl.DateTimeFormatPartTypes)=>parts.find(item=>item.type===type)?.value??"00";const date=`${part("year")}-${part("month")}-${part("day")}`;const hour=Number(part("hour"));const available=[...new Set(beaches.flatMap(beach=>beach.hourlyConditions?.map(item=>item.time.slice(0,16))??[]).filter(time=>time.startsWith(date)))].sort();return[0,2,4,6].map((offset,index)=>{const target=`${date}T${String(Math.min(23,hour+offset)).padStart(2,"0")}:00`;const time=available.reduce<string|undefined>((best,item)=>!best||Math.abs(comparable(item)-comparable(target))<Math.abs(comparable(best)-comparable(target))?item:best,undefined);return time?{time,label:index===0?"Ahora":`+${offset} h`,shortLabel:`${time.slice(11,16)} h`}:undefined}).filter((item):item is TimeOption=>Boolean(item)).filter((item,index,list)=>list.findIndex(other=>other.time===item.time)===index)}

export function getEvolution(beach:Beach){const today=beach.hourlyConditions?.[0]?.time.slice(0,10);const points=(beach.hourlyConditions??[]).filter(item=>item.time.startsWith(today??"")&&Number(item.time.slice(11,13))>=8&&Number(item.time.slice(11,13))<=22).filter((_,index)=>index%2===0).map(item=>{const projected=beachAtTime(beach,item.time);return{time:item.time,score:calculateBeachScore(projected),excluded:Boolean(getBeachExclusion(projected))}});return points.length<=6?points:points.filter((_,index)=>index===0||index===points.length-1||index%Math.ceil(points.length/6)===0).slice(0,7)}

export function getBestTimeWindow(beach:Beach){const today=beach.hourlyConditions?.[0]?.time.slice(0,10);const points=(beach.hourlyConditions??[]).filter(item=>item.time.startsWith(today??"")&&Number(item.time.slice(11,13))>=8&&Number(item.time.slice(11,13))<=22).map(item=>{const projected=beachAtTime(beach,item.time);return{time:item.time,score:calculateBeachScore(projected),excluded:Boolean(getBeachExclusion(projected))}}).filter(item=>!item.excluded);if(!points.length)return undefined;const bestScore=Math.max(...points.map(item=>item.score));const bestIndex=points.findIndex(item=>item.score===bestScore);let start=bestIndex;let end=bestIndex;while(start>0&&points[start-1].score>=bestScore-3)start-=1;while(end<points.length-1&&points[end+1].score>=bestScore-3)end+=1;const startLabel=points[start].time.slice(11,16);const endLabel=points[end].time.slice(11,16);return{start:points[start].time,end:points[end].time,score:bestScore,label:startLabel===endLabel?`${startLabel} h`:`${startLabel}–${endLabel} h`}}
