import type { Beach,BeachHourlyConditions,MetricKey } from "./types";
import { calculateBeachScore,getBeachExclusion } from "./scoring";
import { BATHING_WINDOW,localDateAndHour,selectForecastDate } from "./hourly-options";

export { BATHING_WINDOW,getTodayTimeOptions } from "./hourly-options";

const HOURLY_KEYS=( ["waterTemperature","airTemperature","windSpeed","windGust","windDirection","rainProbability","waveHeight","waveDirection","wavePeriod","swellWaveHeight","swellWaveDirection","swellWavePeriod","oceanCurrentVelocity","oceanCurrentDirection"] as const) satisfies readonly (keyof BeachHourlyConditions)[];
const WEATHER_KEYS=new Set<MetricKey>(["airTemperature","windSpeed","windGust","rainProbability"]);
const comparable=(value:string)=>Date.parse(`${value.slice(0,16)}:00Z`);
export function closestHourlyCondition(beach:Beach,targetTime:string){return beach.hourlyConditions?.reduce<BeachHourlyConditions|undefined>((best,item)=>!best||Math.abs(comparable(item.time)-comparable(targetTime))<Math.abs(comparable(best.time)-comparable(targetTime))?item:best,undefined)}

export function beachAtTime(beach:Beach,targetTime?:string):Beach{if(!targetTime)return beach;const point=closestHourlyCondition(beach,targetTime);if(!point)return beach;const projected={...beach,metricMetadata:{...beach.metricMetadata}};for(const key of HOURLY_KEYS){const value=point[key];if(value!==undefined)(projected as unknown as Record<string,unknown>)[key]=value}for(const key of Object.keys(projected.metricMetadata??{}) as MetricKey[]){if(key==="sanitaryStatus"||key==="jellyfishRisk"||key==="occupancy")continue;projected.metricMetadata![key]={...projected.metricMetadata![key]!,validFor:point.time,source:WEATHER_KEYS.has(key)?beach.sources?.weather?.source:beach.sources?.sea?.source}}return projected}

export function getEvolution(beach:Beach,now=new Date()){const date=selectForecastDate(beach.hourlyConditions?.map(item=>item.time)??[],now);const points=(beach.hourlyConditions??[]).filter(item=>item.time.startsWith(date??"")&&Number(item.time.slice(11,13))>=8&&Number(item.time.slice(11,13))<=22).filter((_,index)=>index%2===0).map(item=>{const projected=beachAtTime(beach,item.time);return{time:item.time,score:calculateBeachScore(projected),excluded:Boolean(getBeachExclusion(projected))}});return points.length<=6?points:points.filter((_,index)=>index===0||index===points.length-1||index%Math.ceil(points.length/6)===0).slice(0,7)}

export function getBestTimeWindow(beach:Beach,now=new Date()){const local=localDateAndHour(now);const firstAvailableDate=beach.hourlyConditions?.[0]?.time.slice(0,10);const date=beach.hourlyConditions?.some(item=>item.time.startsWith(local.date))?local.date:firstAvailableDate;const earliestHour=date===local.date?Math.max(BATHING_WINDOW.startHour,local.hour):BATHING_WINDOW.startHour;const points=(beach.hourlyConditions??[]).filter(item=>item.time.startsWith(date??"")&&Number(item.time.slice(11,13))>=earliestHour&&Number(item.time.slice(11,13))<=BATHING_WINDOW.endHour).map(item=>{const projected=beachAtTime(beach,item.time);return{time:item.time,score:calculateBeachScore(projected),excluded:Boolean(getBeachExclusion(projected))}}).filter(item=>!item.excluded);if(!points.length)return undefined;const bestScore=Math.max(...points.map(item=>item.score));const bestIndex=points.findIndex(item=>item.score===bestScore);let start=bestIndex;let end=bestIndex;while(start>0&&points[start-1].score>=bestScore-3)start-=1;while(end<points.length-1&&points[end+1].score>=bestScore-3)end+=1;const startLabel=points[start].time.slice(11,16);const endLabel=points[end].time.slice(11,16);return{start:points[start].time,end:points[end].time,score:bestScore,label:startLabel===endLabel?`${startLabel} h`:`${startLabel}–${endLabel} h`}}
