import type { Beach } from "./types";
const updatedAt="2026-08-24T09:15:00+02:00";
export const beaches:Beach[]=[
{id:"1",slug:"las-dunas",name:"Playa de Las Dunas",municipality:"Torrox",latitude:36.733,longitude:-3.963,waterTemperature:25.4,airTemperature:29,windSpeed:8,windGust:14,waveHeight:.2,jellyfishRisk:1,occupancy:"low",sanitaryStatus:"safe",rainProbability:2,updatedAt},
{id:"2",slug:"las-lindes",name:"Las Lindes",municipality:"Torrox",latitude:36.735,longitude:-3.976,waterTemperature:25.1,airTemperature:29,windSpeed:9,windGust:16,waveHeight:.2,jellyfishRisk:3,occupancy:"medium",sanitaryStatus:"safe",rainProbability:2,updatedAt},
{id:"3",slug:"el-morche",name:"El Morche",municipality:"Torrox",latitude:36.738,longitude:-4.003,waterTemperature:25.3,airTemperature:29,windSpeed:10,windGust:17,waveHeight:.3,jellyfishRisk:2,occupancy:"medium",sanitaryStatus:"safe",rainProbability:3,updatedAt},
{id:"4",slug:"ferrara",name:"Ferrara",municipality:"Torrox",latitude:36.729,longitude:-3.957,waterTemperature:25.2,airTemperature:30,windSpeed:11,windGust:19,waveHeight:.3,jellyfishRisk:4,occupancy:"high",sanitaryStatus:"safe",rainProbability:2,updatedAt},
{id:"5",slug:"calaceite",name:"Calaceite",municipality:"Torrox",latitude:36.743,longitude:-3.912,waterTemperature:24.9,airTemperature:29,windSpeed:7,windGust:13,waveHeight:.2,jellyfishRisk:6,occupancy:"low",sanitaryStatus:"safe",rainProbability:2,updatedAt},
{id:"6",slug:"burriana",name:"Burriana",municipality:"Nerja",latitude:36.752,longitude:-3.867,waterTemperature:24.8,airTemperature:30,windSpeed:8,windGust:15,waveHeight:.3,jellyfishRisk:8,occupancy:"high",sanitaryStatus:"safe",rainProbability:1,updatedAt},
{id:"7",slug:"el-playazo-nerja",name:"El Playazo",municipality:"Nerja",latitude:36.739,longitude:-3.897,waterTemperature:25,airTemperature:30,windSpeed:9,windGust:17,waveHeight:.3,jellyfishRisk:5,occupancy:"medium",sanitaryStatus:"safe",rainProbability:2,updatedAt},
{id:"8",slug:"maro",name:"Maro",municipality:"Nerja",latitude:36.756,longitude:-3.835,waterTemperature:24.6,airTemperature:29,windSpeed:6,windGust:12,waveHeight:.2,jellyfishRisk:4,occupancy:"medium",sanitaryStatus:"safe",rainProbability:1,updatedAt},
{id:"9",slug:"rincon-victoria",name:"Rincón de la Victoria",municipality:"Rincón de la Victoria",latitude:36.713,longitude:-4.283,waterTemperature:24.7,airTemperature:29,windSpeed:12,windGust:20,waveHeight:.4,jellyfishRisk:10,occupancy:"medium",sanitaryStatus:"safe",rainProbability:4,updatedAt},
{id:"10",slug:"cala-del-moral",name:"La Cala del Moral",municipality:"Rincón de la Victoria",latitude:36.716,longitude:-4.311,waterTemperature:24.6,airTemperature:29,windSpeed:13,windGust:22,waveHeight:.4,jellyfishRisk:12,occupancy:"medium",sanitaryStatus:"safe",rainProbability:4,updatedAt},
{id:"11",slug:"el-palo",name:"El Palo",municipality:"Málaga",latitude:36.72,longitude:-4.357,waterTemperature:24.5,airTemperature:30,windSpeed:11,windGust:19,waveHeight:.3,jellyfishRisk:9,occupancy:"high",sanitaryStatus:"safe",rainProbability:5,updatedAt},
{id:"12",slug:"pedregalejo",name:"Pedregalejo",municipality:"Málaga",latitude:36.721,longitude:-4.374,waterTemperature:24.6,airTemperature:30,windSpeed:12,windGust:21,waveHeight:.3,jellyfishRisk:11,occupancy:"high",sanitaryStatus:"safe",rainProbability:5,updatedAt},
{id:"13",slug:"malagueta",name:"La Malagueta",municipality:"Málaga",latitude:36.718,longitude:-4.404,waterTemperature:24.4,airTemperature:31,windSpeed:14,windGust:24,waveHeight:.5,jellyfishRisk:14,occupancy:"high",sanitaryStatus:"safe",rainProbability:4,updatedAt},
{id:"14",slug:"misericordia",name:"Misericordia",municipality:"Málaga",latitude:36.685,longitude:-4.448,waterTemperature:24.3,airTemperature:31,windSpeed:15,windGust:27,waveHeight:.5,jellyfishRisk:8,occupancy:"medium",sanitaryStatus:"warning",sanitaryMessage:"Precaución temporal tras el último control de calidad del agua.",rainProbability:4,updatedAt},
{id:"15",slug:"guadalmar",name:"Guadalmar",municipality:"Málaga",latitude:36.654,longitude:-4.477,waterTemperature:24.2,airTemperature:30,windSpeed:19,windGust:33,waveHeight:.7,jellyfishRisk:16,occupancy:"low",sanitaryStatus:"safe",rainProbability:6,updatedAt},
{id:"16",slug:"los-alamos",name:"Los Álamos",municipality:"Torremolinos",latitude:36.631,longitude:-4.491,waterTemperature:24.1,airTemperature:30,windSpeed:17,windGust:29,waveHeight:.6,jellyfishRisk:13,occupancy:"high",sanitaryStatus:"safe",rainProbability:5,updatedAt},
{id:"17",slug:"la-carihuela",name:"La Carihuela",municipality:"Torremolinos",latitude:36.61,longitude:-4.507,waterTemperature:24.4,airTemperature:30,windSpeed:12,windGust:21,waveHeight:.4,jellyfishRisk:7,occupancy:"high",sanitaryStatus:"safe",rainProbability:4,updatedAt},
{id:"18",slug:"butibamba",name:"Butibamba",municipality:"La Cala de Mijas",latitude:36.502,longitude:-4.687,waterTemperature:23.9,airTemperature:29,windSpeed:10,windGust:18,waveHeight:.3,jellyfishRisk:5,occupancy:"medium",sanitaryStatus:"safe",rainProbability:3,updatedAt},
{id:"19",slug:"el-bombo",name:"El Bombo",municipality:"Mijas",latitude:36.5,longitude:-4.674,waterTemperature:24,airTemperature:29,windSpeed:9,windGust:16,waveHeight:.3,jellyfishRisk:6,occupancy:"low",sanitaryStatus:"safe",rainProbability:3,updatedAt},
{id:"20",slug:"calahonda",name:"Calahonda",municipality:"Mijas",latitude:36.489,longitude:-4.718,waterTemperature:23.8,airTemperature:29,windSpeed:16,windGust:28,waveHeight:.6,jellyfishRisk:18,occupancy:"medium",sanitaryStatus:"closed",sanitaryMessage:"Baño prohibido temporalmente por presencia elevada de E. coli.",rainProbability:4,updatedAt}
];
