import type { Beach,Priority } from "./types";
export const SCORE_WEIGHTS={warmWater:22,lowWind:18,lowGust:10,calmSea:18,lowJellyfish:14,lowRain:10,lowOccupancy:8} as const;
export const DANGEROUS_CONDITIONS={windSpeedKmh:45,windGustKmh:70,waveHeightM:2.5} as const;
export type BeachExclusion={code:"closed"|"strong-wind"|"strong-gusts"|"high-waves";reason:string};
const clamp=(value:number)=>Math.max(0,Math.min(1,value)); const occupancyValue={low:1,medium:.55,high:.15} as const;
export function calculateDataCompleteness(beach:Beach){const families=[beach.airTemperature!==undefined||beach.windSpeed!==undefined||beach.rainProbability!==undefined,beach.waterTemperature!==undefined,beach.waveHeight!==undefined,beach.sanitaryStatus!=="unknown",beach.jellyfishRisk!==undefined,beach.occupancy!==undefined];return Math.round(families.filter(Boolean).length/families.length*100)}
export function getBeachExclusion(beach:Beach):BeachExclusion|undefined{if(beach.sanitaryStatus==="closed")return{code:"closed",reason:beach.sanitaryMessage??"Baño prohibido temporalmente."};if((beach.waveHeight??0)>=DANGEROUS_CONDITIONS.waveHeightM)return{code:"high-waves",reason:"Oleaje previsto demasiado alto para recomendar el baño."};if((beach.windGust??0)>=DANGEROUS_CONDITIONS.windGustKmh)return{code:"strong-gusts",reason:"Rachas previstas demasiado intensas para recomendar el baño."};if((beach.windSpeed??0)>=DANGEROUS_CONDITIONS.windSpeedKmh)return{code:"strong-wind",reason:"Viento previsto demasiado intenso para recomendar el baño."};return undefined}
export function calculateBeachScore(beach:Beach,priorities:Priority[]=[]){if(getBeachExclusion(beach))return 0;const boost=(key:Priority)=>priorities.includes(key)?1.65:1;const factors:{value:number;weight:number}[]=[];const add=(value:number|undefined,weight:number,normalize:(value:number)=>number)=>{if(value!==undefined)factors.push({value:normalize(value),weight})};add(beach.waterTemperature,SCORE_WEIGHTS.warmWater*boost("warmWater"),v=>clamp((v-18)/8));add(beach.windSpeed,SCORE_WEIGHTS.lowWind*boost("lowWind"),v=>clamp(1-v/30));add(beach.windGust,SCORE_WEIGHTS.lowGust,v=>clamp(1-v/45));add(beach.waveHeight,SCORE_WEIGHTS.calmSea*boost("calmSea"),v=>clamp(1-v/1.4));add(beach.jellyfishRisk,SCORE_WEIGHTS.lowJellyfish*boost("lowJellyfish"),v=>clamp(1-v/60));add(beach.rainProbability,SCORE_WEIGHTS.lowRain,v=>clamp(1-v/70));if(beach.occupancy!==undefined)factors.push({value:occupancyValue[beach.occupancy],weight:SCORE_WEIGHTS.lowOccupancy*boost("lowOccupancy")});if(!factors.length)return 0;const totalWeight=factors.reduce((sum,item)=>sum+item.weight,0);const base=factors.reduce((sum,item)=>sum+item.value*item.weight,0)/totalWeight*100;return Math.round(beach.sanitaryStatus==="warning"?base*.55:base)}
export function explainRecommendation(beach:Beach){const exclusion=getBeachExclusion(beach);if(exclusion)return exclusion.reason;const reasons:string[]=[];if((beach.waterTemperature??0)>=24.5)reasons.push("el agua está cálida");if((beach.windSpeed??99)<=10)reasons.push("sopla poco viento");if((beach.waveHeight??99)<=.3)reasons.push("el mar está tranquilo");if((beach.jellyfishRisk??99)<=5)reasons.push("el riesgo de medusas es muy bajo");if(beach.occupancy==="low")reasons.push("se espera poca gente");if(!reasons.length)reasons.push("las condiciones disponibles son favorables");const joined=reasons.length>1?`${reasons.slice(0,-1).join(", ")} y ${reasons.at(-1)}`:reasons[0];const sanitaryNote=beach.sanitaryStatus==="unknown"?" El estado sanitario específico no está disponible y no altera por sí solo la puntuación.":"";return`Hoy ${beach.name} es una buena opción porque ${joined}.${sanitaryNote}`}
