import type { Beach,JellyfishObservationStatus,Priority } from "./types";
export const SCORE_WEIGHTS={warmWater:22,lowWind:18,lowGust:10,calmSea:18,lowJellyfish:14,lowRain:10,lowOccupancy:8} as const;
export const DANGEROUS_CONDITIONS={windSpeedKmh:45,windGustKmh:70,waveHeightM:2.5} as const;
export type ScoredNumericMetric="waterTemperature"|"windSpeed"|"windGust"|"waveHeight"|"jellyfishRisk"|"rainProbability";
export type BeachExclusion={code:"closed"|"strong-wind"|"strong-gusts"|"high-waves";reason:string};
const clamp=(value:number)=>Math.max(0,Math.min(1,value)); const occupancyValue={low:1,medium:.55,high:.15} as const;
export const JELLYFISH_PREFERENCE_ADJUSTMENTS:Record<JellyfishObservationStatus,number>={recent_no_sightings:2,no_recent_reports:0,unknown:0,recent_sighting:-4,multiple_recent_sightings:-7,strong_recent_presence:-10};
export const getJellyfishPreferenceAdjustment=(beach:Pick<Beach,"jellyfishObservation">)=>JELLYFISH_PREFERENCE_ADJUSTMENTS[beach.jellyfishObservation?.status??"unknown"];
export function getMetricConditionValue(metric:ScoredNumericMetric,value:number){if(metric==="waterTemperature")return clamp((value-18)/8);if(metric==="windSpeed")return clamp(1-value/30);if(metric==="windGust")return clamp(1-value/45);if(metric==="waveHeight")return clamp(1-value/1.4);if(metric==="jellyfishRisk")return clamp(1-value/60);return clamp(1-value/70)}
export function calculateDataCompleteness(beach:Beach){const jellyfishAvailable=beach.jellyfishRisk!==undefined||beach.jellyfishObservation!==undefined&&beach.jellyfishObservation.status!=="unknown";const families=[beach.airTemperature!==undefined||beach.windSpeed!==undefined||beach.rainProbability!==undefined,beach.waterTemperature!==undefined,beach.waveHeight!==undefined,beach.sanitaryStatus!=="unknown",jellyfishAvailable,beach.occupancy!==undefined];return Math.round(families.filter(Boolean).length/families.length*100)}
export function getBeachExclusion(beach:Beach):BeachExclusion|undefined{if(beach.sanitaryStatus==="closed")return{code:"closed",reason:beach.sanitaryMessage??"Baño prohibido temporalmente."};if((beach.waveHeight??0)>=DANGEROUS_CONDITIONS.waveHeightM)return{code:"high-waves",reason:"Oleaje previsto demasiado alto para recomendar el baño."};if((beach.windGust??0)>=DANGEROUS_CONDITIONS.windGustKmh)return{code:"strong-gusts",reason:"Rachas previstas demasiado intensas para recomendar el baño."};if((beach.windSpeed??0)>=DANGEROUS_CONDITIONS.windSpeedKmh)return{code:"strong-wind",reason:"Viento previsto demasiado intenso para recomendar el baño."};return undefined}
export function calculateBeachScorePrecise(beach:Beach,priorities:Priority[]=[]){if(getBeachExclusion(beach))return 0;const boost=(key:Priority)=>priorities.includes(key)?1.65:1;const factors:{value:number;weight:number}[]=[];const add=(metric:ScoredNumericMetric,value:number|undefined,weight:number)=>{if(value!==undefined)factors.push({value:getMetricConditionValue(metric,value),weight})};add("waterTemperature",beach.waterTemperature,SCORE_WEIGHTS.warmWater*boost("warmWater"));add("windSpeed",beach.windSpeed,SCORE_WEIGHTS.lowWind*boost("lowWind"));add("windGust",beach.windGust,SCORE_WEIGHTS.lowGust);add("waveHeight",beach.waveHeight,SCORE_WEIGHTS.calmSea*boost("calmSea"));add("jellyfishRisk",beach.jellyfishRisk,SCORE_WEIGHTS.lowJellyfish*boost("lowJellyfish"));add("rainProbability",beach.rainProbability,SCORE_WEIGHTS.lowRain);if(beach.occupancy!==undefined)factors.push({value:occupancyValue[beach.occupancy],weight:SCORE_WEIGHTS.lowOccupancy*boost("lowOccupancy")});if(!factors.length)return 0;const totalWeight=factors.reduce((sum,item)=>sum+item.weight,0);const base=factors.reduce((sum,item)=>sum+item.value*item.weight,0)/totalWeight*100;const sanitaryAdjusted=beach.sanitaryStatus==="warning"?base*.55:base;const jellyfishAdjustment=priorities.includes("lowJellyfish")?getJellyfishPreferenceAdjustment(beach):0;return Math.max(0,Math.min(100,sanitaryAdjusted+jellyfishAdjustment))}
export function calculateBeachScore(beach:Beach,priorities:Priority[]=[]){return Math.round(calculateBeachScorePrecise(beach,priorities))}
export function explainRecommendation(beach:Beach){const exclusion=getBeachExclusion(beach);if(exclusion)return exclusion.reason;const reasons:string[]=[];if((beach.waterTemperature??0)>=24.5)reasons.push("el agua está cálida");if((beach.windSpeed??99)<=10)reasons.push("sopla poco viento");if((beach.waveHeight??99)<=.3)reasons.push("el mar está tranquilo");if((beach.jellyfishRisk??99)<=5)reasons.push("el riesgo de medusas es muy bajo");if(beach.occupancy==="low")reasons.push("se espera poca gente");if(!reasons.length)reasons.push("las condiciones disponibles son favorables");const joined=reasons.length>1?`${reasons.slice(0,-1).join(", ")} y ${reasons.at(-1)}`:reasons[0];const sanitaryNote=beach.sanitaryStatus==="unknown"?" El estado sanitario específico no está disponible y no altera por sí solo la puntuación.":"";return`Hoy ${beach.name} es una buena opción porque ${joined}.${sanitaryNote}`}
