"use client";

import Link from "next/link";
import { useMemo,useState } from "react";
import { calculateBeachScore,getBeachExclusion } from "@/lib/scoring";
import { distanceInKm } from "@/lib/distance";
import { getGoogleMapsDirectionsUrl } from "@/lib/maps";
import { getBeachSummaryMetrics } from "@/lib/display-metrics";
import { beachAtTime,getTodayTimeOptions } from "@/lib/hourly";
import { findNearbyRecommendation } from "@/lib/nearby-recommendation";
import type { Beach,Priority,SortOption } from "@/lib/types";
import { Header } from "./Header";
import { BeachFilters } from "./BeachFilters";
import { BeachRanking } from "./BeachRanking";
import { BeachScore } from "./BeachScore";
import { SanitaryStatus } from "./SanitaryStatus";
import { BeachCard } from "./BeachCard";

export function BeachExplorer({initialBeaches}:{initialBeaches:Beach[]}) {
 const [priorities,setPriorities]=useState<Priority[]>([]);const [sort,setSort]=useState<SortOption>("score");const [location,setLocation]=useState<{lat:number;lon:number}>();const [locating,setLocating]=useState(false);const [locationError,setLocationError]=useState("");const [showTimeSelector,setShowTimeSelector]=useState(false);const [selectedTime,setSelectedTime]=useState<string>();
 const timeOptions=useMemo(()=>getTodayTimeOptions(initialBeaches),[initialBeaches]);const activeBeaches=useMemo(()=>initialBeaches.map(beach=>beachAtTime(beach,selectedTime)),[initialBeaches,selectedTime]);
 const ranked=useMemo(()=>activeBeaches.map(beach=>({beach,score:calculateBeachScore(beach,priorities),distance:location?distanceInKm(location.lat,location.lon,beach.latitude,beach.longitude):undefined})).filter(item=>!getBeachExclusion(item.beach)).sort((a,b)=>{if(sort==="warmest")return(b.beach.waterTemperature??-Infinity)-(a.beach.waterTemperature??-Infinity);if(sort==="wind")return(a.beach.windSpeed??Infinity)-(b.beach.windSpeed??Infinity);if(sort==="waves")return(a.beach.waveHeight??Infinity)-(b.beach.waveHeight??Infinity);if(sort==="distance")return(a.distance??Infinity)-(b.distance??Infinity);return b.score-a.score}),[activeBeaches,priorities,sort,location]);
 const notRecommended=activeBeaches.map(beach=>({beach,exclusion:getBeachExclusion(beach)})).filter((item):item is {beach:Beach;exclusion:NonNullable<ReturnType<typeof getBeachExclusion>>}=>Boolean(item.exclusion));const best=ranked[0];const bestMetrics=best?getBeachSummaryMetrics(best.beach):[];const nearby=location?findNearbyRecommendation(activeBeaches,location,best?.beach.id):undefined;const mockMode=initialBeaches.every(beach=>beach.dataMode==="mock");const jellyfishAvailable=activeBeaches.some(beach=>beach.jellyfishRisk!==undefined);const occupancyAvailable=activeBeaches.some(beach=>beach.occupancy!==undefined);const selectedTimeLabel=selectedTime?`${selectedTime.slice(11,16)} h`:undefined;
 const locate=()=>{if(!navigator.geolocation){setLocationError("Tu navegador no permite compartir la ubicación.");return}setLocating(true);setLocationError("");navigator.geolocation.getCurrentPosition(position=>{setLocation({lat:position.coords.latitude,lon:position.coords.longitude});setLocating(false)},()=>{setLocationError("No hemos podido obtener tu ubicación. Revisa los permisos del navegador.");setLocating(false)})};
 const toggle=(priority:Priority)=>{if((priority==="lowJellyfish"&&!jellyfishAvailable)||(priority==="lowOccupancy"&&!occupancyAvailable))return;setPriorities(current=>current.includes(priority)?current.filter(item=>item!==priority):[...current,priority])};
 return <><Header onLocate={locate} locating={locating} hasLocation={Boolean(location)}/><main><section className="hero-grid overflow-hidden bg-[#075b78] text-white"><div className="mx-auto max-w-6xl px-4 pb-24 pt-10 sm:px-6 sm:pb-28 sm:pt-14"><div className="mb-8 max-w-2xl"><p className="mb-3 flex items-center gap-2 text-sm font-bold text-[#a9e9df]"><span className="size-2 rounded-full bg-[#70d4c5] shadow-[0_0_0_5px_rgba(112,212,197,.14)]"/>{mockMode?"Costa del Sol · Datos de demostración":"Costa del Sol · Fuentes reales por playa"}</p><h1 className="text-4xl font-extrabold leading-[1.08] tracking-[-.04em] sm:text-6xl">¿A qué playa<br className="sm:hidden"/> voy hoy?</h1><p className="mt-4 max-w-xl text-base leading-7 text-white/70 sm:text-lg">Comparamos el mar, el viento y la calidad del agua para encontrar tu mejor baño.</p></div>
 {best?<div className="relative max-w-4xl overflow-hidden rounded-[1.75rem] border border-white/15 bg-white/10 p-5 shadow-[0_24px_70px_rgba(0,25,38,.25)] backdrop-blur sm:p-8"><div className="absolute -right-16 -top-16 size-56 rounded-full border-[40px] border-[#70d4c5]/10"/><div className="relative flex flex-col gap-6 sm:flex-row sm:items-center"><div className="flex-1"><p className="mb-3 text-xs font-extrabold uppercase tracking-[.18em] text-[#70d4c5]">{selectedTimeLabel?`Mejor opción a las ${selectedTimeLabel}`:"Mejor opción ahora"}</p><h2 className="text-3xl font-extrabold tracking-tight sm:text-4xl">{best.beach.name}</h2><p className="mt-1 text-white/65">{best.beach.municipality}{best.distance!==undefined&&` · ${best.distance.toFixed(1)} km de ti`}</p><div className="mt-5"><SanitaryStatus status={best.beach.sanitaryStatus}/></div></div><BeachScore score={best.score} size="large" dark/></div><div className="relative mt-6 grid grid-cols-4 gap-2 border-t border-white/15 pt-5">{bestMetrics.map(metric=><HeroMetric key={metric.label} symbol={metric.icon} value={metric.value} label={metric.label} origin={metric.origin}/>)}</div><div className="relative mt-6 grid gap-2 sm:flex"><Link href={`/playa/${best.beach.slug}`} className="inline-flex min-h-12 items-center justify-center rounded-xl bg-[#70d4c5] px-5 text-sm font-extrabold text-[#06455d] transition hover:bg-[#93e3d7]">Ver detalles <span className="ml-2">→</span></Link><a href={getGoogleMapsDirectionsUrl(best.beach.latitude,best.beach.longitude)} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 items-center justify-center rounded-xl border border-white/25 bg-white/10 px-5 text-sm font-extrabold text-white transition hover:bg-white/20">⌖&nbsp; Cómo llegar</a></div></div>:<div className="max-w-4xl rounded-[1.75rem] border border-white/15 bg-white/10 p-6 backdrop-blur sm:p-8"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-[#70d4c5]">Sin recomendación segura</p><h2 className="mt-3 text-2xl font-extrabold">Las condiciones requieren precaución</h2><p className="mt-2 max-w-xl text-white/70">No hay una playa que supere ahora los criterios de seguridad definidos.</p></div>}
 <div className="mt-4 flex max-w-4xl flex-col gap-2 sm:flex-row"><button type="button" onClick={locate} disabled={locating} className="min-h-11 rounded-xl border border-white/25 bg-white/10 px-4 text-sm font-extrabold transition hover:bg-white/20 disabled:opacity-60">{locating?"Buscando ubicación…":"⌖ Buscar una más cerca de mí"}</button><button type="button" onClick={()=>setShowTimeSelector(current=>!current)} className="min-h-11 rounded-xl border border-white/25 bg-white/10 px-4 text-sm font-extrabold transition hover:bg-white/20">◷ Voy más tarde</button></div>
 {showTimeSelector&&<div className="mt-3 max-w-4xl rounded-2xl border border-white/15 bg-[#064f69] p-4"><p className="text-sm font-extrabold">¿A qué hora quieres ir hoy?</p>{timeOptions.length?<div className="mt-3 grid grid-cols-2 gap-2 sm:flex">{timeOptions.map(option=><button key={option.time} type="button" onClick={()=>setSelectedTime(option.time)} className={`min-h-11 rounded-xl px-4 text-sm font-extrabold transition ${selectedTime===option.time?"bg-[#70d4c5] text-[#06455d]":"bg-white/10 text-white hover:bg-white/20"}`}><span>{option.label}</span><span className="ml-2 opacity-70">{option.shortLabel}</span></button>)}</div>:<p className="mt-2 text-sm font-bold text-white/70">No quedan franjas recomendadas para baño hoy.</p>}</div>}
 {location&&nearby&&<div className="mt-3 max-w-4xl rounded-2xl border border-[#70d4c5]/35 bg-[#064f69] p-4 sm:flex sm:items-center sm:justify-between sm:gap-5"><div><p className="text-xs font-extrabold uppercase tracking-[.14em] text-[#70d4c5]">Mejor opción más cerca de ti{selectedTimeLabel&&` · ${selectedTimeLabel}`}</p><h3 className="mt-1 text-xl font-extrabold">{nearby.beach.name}</h3><p className="mt-1 text-sm text-white/75">{nearby.distance.toFixed(1)} km aprox. · {nearby.reason}</p><p className="mt-1 text-xs text-white/55">Hemos priorizado una buena opción reduciendo el desplazamiento.{best&&` La mejor opción general ${selectedTimeLabel?`a las ${selectedTimeLabel}`:"ahora"} sigue siendo ${best.beach.name} · ${best.score}/100.`}</p></div><div className="mt-3 flex items-center gap-3 sm:mt-0"><BeachScore score={nearby.score} dark/><Link href={`/playa/${nearby.beach.slug}`} className="text-sm font-extrabold text-[#a9e9df] hover:underline">Ver playa →</Link></div></div>}</div></section>
 <div className="mx-auto -mt-14 max-w-6xl px-4 pb-16 sm:px-6"><BeachFilters selected={priorities} onToggle={toggle} sort={sort} onSort={setSort} canSortDistance={Boolean(location)} jellyfishAvailable={jellyfishAvailable} occupancyAvailable={occupancyAvailable}/>{locationError&&<p role="alert" className="mt-3 rounded-xl bg-red-50 px-4 py-3 text-sm font-bold text-red-700">{locationError}</p>}<div className="mt-10 grid gap-10 lg:grid-cols-[1fr_300px]"><BeachRanking beaches={ranked} timeLabel={selectedTimeLabel}/><aside className="space-y-4"><div className="rounded-3xl bg-[#dff5f0] p-6"><span className="text-2xl">◎</span><h2 className="mt-3 text-lg font-extrabold">Datos para decidir mejor</h2><p className="mt-2 text-sm leading-6 text-[#4c6b73]">El score usa solo métricas disponibles. Un cierre o una condición peligrosa siempre tiene prioridad.</p></div>{mockMode&&<div className="rounded-3xl border border-amber-200 bg-amber-50 p-6"><p className="text-xs font-extrabold uppercase tracking-[.16em] text-amber-700">Modo demostración</p><p className="mt-3 text-sm leading-6 text-amber-900">Las condiciones mostradas son simuladas y sirven para validar la experiencia.</p></div>}</aside></div>{notRecommended.length>0&&<section className="mt-14 border-t border-[#d7dfdc] pt-10"><p className="mb-1 text-xs font-extrabold uppercase tracking-[.16em] text-red-600">Motivo conocido</p><h2 className="mb-4 text-2xl font-extrabold">Playas no recomendadas {selectedTimeLabel?`a las ${selectedTimeLabel}`:"ahora"}</h2><div className="grid gap-3">{notRecommended.map(({beach,exclusion})=><div key={beach.id}><p className="mb-2 px-1 text-sm font-bold text-red-700">{exclusion.reason}</p><BeachCard beach={beach} score={0} distance={location?distanceInKm(location.lat,location.lon,beach.latitude,beach.longitude):undefined}/></div>)}</div></section>}</div></main>
 <footer className="border-t border-[#dce5e4] bg-white"><div className="mx-auto flex max-w-6xl flex-col gap-3 px-4 py-8 text-sm text-[#647b86] sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><span className="font-extrabold text-[#075b78]">≈ Playa Hoy</span><span className="ml-2">Diseño y desarrollo por JPT</span></div><p>{mockMode?"Datos de demostración · MVP":<>Fuentes: <a href="https://opendata.aemet.es/dist/index.html" target="_blank" rel="noopener noreferrer" className="font-bold text-[#075b78] hover:underline">AEMET</a>, <a href="https://open-meteo.com/" target="_blank" rel="noopener noreferrer" className="font-bold text-[#075b78] hover:underline">Open-Meteo</a> y <a href="https://www.medusapp.net/acercade.html" target="_blank" rel="noopener noreferrer" className="font-bold text-[#075b78] hover:underline">MedusApp · CC BY-NC-SA 4.0</a></>}</p></div></footer></>;
}

function HeroMetric({symbol,value,label,origin}:{symbol:string;value:string;label:string;origin?:string}){return <div><span className="text-base font-bold text-[#70d4c5]">{symbol}</span><p className="mt-1 text-lg font-extrabold sm:text-2xl">{value}</p><p className="text-[11px] text-white/55 sm:text-xs">{label}{origin&&` · ${origin}`}</p></div>}
