import "server-only";
import { getCache } from "@vercel/functions";
import { unstable_cache } from "next/cache";
import { retryAfterMilliseconds } from "../provider-utils";
import { AEMET_MUNICIPALITY_CODES } from "../aemet-config";

export { retryAfterMilliseconds } from "../provider-utils";
export { AEMET_MUNICIPALITY_CODES } from "../aemet-config";

export type WeatherHour={time:string;airTemperature?:number;windSpeed?:number;windGust?:number;windDirection?:number;rainProbability?:number};
export type WeatherResult={airTemperature?:number;windSpeed?:number;windGust?:number;windDirection?:number;rainProbability?:number;hourly:WeatherHour[];updatedAt?:string;validFor?:string;source:string;sourceUrl:string;stale?:boolean};
const API_BASE="https://opendata.aemet.es/opendata/api";const SOURCE_URL="https://opendata.aemet.es/dist/index.html";const TIMEZONE="Europe/Madrid";
export const AEMET_CACHE_SECONDS=3600;
const LAST_VALID_SECONDS=48*60*60;const TIMEOUT_MS=12_000;export const AEMET_REQUEST_SPACING_MS=1000;
type Scalar=number|string|null;type TimedValue={periodo?:string;value?:Scalar;direccion?:string|string[];velocidad?:Scalar|Scalar[]};type ForecastDay={fecha?:string;temperatura?:TimedValue[];probPrecipitacion?:TimedValue[];vientoAndRachaMax?:TimedValue[]};type AemetPayload={origen?:{elaborado?:string};elaborado?:string;prediccion?:{dia?:ForecastDay[]}};type MetadataResponse={datos?:string;estado?:number;descripcion?:string};
function localDateAndHour(now=new Date()){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:TIMEZONE,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(now);const part=(type:Intl.DateTimeFormatPartTypes)=>parts.find(item=>item.type===type)?.value??"00";return{date:`${part("year")}-${part("month")}-${part("day")}`,hour:Number(part("hour")),minute:Number(part("minute"))}}
const periodStart=(period?:string)=>{if(!period)return undefined;const value=period.length===4?period.slice(0,2):period;const parsed=Number(value);return Number.isFinite(parsed)?parsed:undefined};const circularHourDistance=(a:number,b:number)=>Math.min(Math.abs(a-b),24-Math.abs(a-b));const closestInstant=(values:TimedValue[]|undefined,hour:number)=>values?.filter(item=>periodStart(item.periodo)!==undefined).reduce<TimedValue|undefined>((best,item)=>!best||circularHourDistance(periodStart(item.periodo)!,hour)<circularHourDistance(periodStart(best.periodo)!,hour)?item:best,undefined);
function intervalContains(period:string,hour:number){if(!/^\d{4}$/.test(period))return false;const start=Number(period.slice(0,2));const end=Number(period.slice(2));return start<end?hour>=start&&hour<end:hour>=start||hour<end}
const closestProbability=(values:TimedValue[]|undefined,hour:number)=>values?.find(item=>item.periodo&&intervalContains(item.periodo,hour))??closestInstant(values,hour);const first=(value:Scalar|Scalar[]|undefined):Scalar|undefined=>Array.isArray(value)?value[0]??undefined:value??undefined;const asNumber=(value:Scalar|Scalar[]|undefined)=>{const candidate=first(value);if(candidate===undefined||candidate===null||candidate==="")return undefined;const parsed=Number(candidate);return Number.isFinite(parsed)?parsed:undefined};const compassDegrees=(value:string|string[]|undefined)=>{const candidate=Array.isArray(value)?value[0]:value;if(!candidate)return undefined;const map:Record<string,number>={N:0,NE:45,E:90,SE:135,S:180,SO:225,O:270,NO:315};return map[candidate]};const wait=(milliseconds:number)=>new Promise(resolve=>setTimeout(resolve,milliseconds));
async function fetchWithRetry(url:string,phase:string){let lastError:unknown;for(let attempt=0;attempt<3;attempt+=1)try{const response=await fetch(url,{cache:"no-store",signal:AbortSignal.timeout(TIMEOUT_MS)});if(response.ok)return response;if(response.status!==429&&response.status<500)return response;lastError=new Error(`${phase} · HTTP ${response.status}`);if(attempt<2)await wait(retryAfterMilliseconds(response.headers.get("retry-after"),attempt))}catch(error){lastError=error;if(attempt<2)await wait(retryAfterMilliseconds(null,attempt))}throw lastError instanceof Error?lastError:new Error(`${phase} · AEMET no respondió`)}
function parseWeather(payload:AemetPayload[]):WeatherResult{const root=payload[0];const days=root?.prediccion?.dia??[];const local=localDateAndHour();const target=localDateAndHour(new Date(Date.now()+(local.minute>=30?3600000:0)));if(!days.length)throw new Error("fase parser · predicción sin días");const hourly=days.flatMap(day=>{const date=day.fecha?.slice(0,10);if(!date)return[];return Array.from({length:24},(_,hour)=>{const temperature=closestInstant(day.temperatura,hour);const rain=closestProbability(day.probPrecipitacion,hour);const windItems=day.vientoAndRachaMax;const wind=closestInstant(windItems?.filter(item=>item.velocidad!==undefined),hour);const gust=closestInstant(windItems?.filter(item=>item.value!==undefined),hour);return{time:`${date}T${String(hour).padStart(2,"0")}:00`,airTemperature:asNumber(temperature?.value),windSpeed:asNumber(wind?.velocidad),windGust:asNumber(gust?.value),windDirection:compassDegrees(wind?.direccion),rainProbability:asNumber(rain?.value)}})}).filter(point=>[point.airTemperature,point.windSpeed,point.windGust,point.windDirection,point.rainProbability].some(value=>value!==undefined));const targetTime=`${target.date}T${String(target.hour).padStart(2,"0")}:00`;const current=hourly.reduce<WeatherHour|undefined>((best,item)=>!best||Math.abs(Date.parse(`${item.time}:00Z`)-Date.parse(`${targetTime}:00Z`))<Math.abs(Date.parse(`${best.time}:00Z`)-Date.parse(`${targetTime}:00Z`))?item:best,undefined);const result:WeatherResult={airTemperature:current?.airTemperature,windSpeed:current?.windSpeed,windGust:current?.windGust,windDirection:current?.windDirection,rainProbability:current?.rainProbability,hourly,updatedAt:root?.elaborado??root?.origen?.elaborado,validFor:current?.time,source:"AEMET OpenData",sourceUrl:SOURCE_URL};if([result.airTemperature,result.windSpeed,result.windGust,result.windDirection,result.rainProbability].every(value=>value===undefined))throw new Error("fase parser · sin métricas utilizables");return result}
const memoryLastValid=new Map<string,WeatherResult>();const lastValidKey=(code:string)=>`last-valid:${code}`;function isWeatherResult(value:unknown):value is WeatherResult{return Boolean(value&&typeof value==="object"&&Array.isArray((value as WeatherResult).hourly)&&typeof (value as WeatherResult).source==="string")}
async function persistLastValid(code:string,result:WeatherResult){memoryLastValid.set(code,result);try{await getCache({namespace:"playa-hoy-aemet"}).set(lastValidKey(code),result,{ttl:LAST_VALID_SECONDS,tags:["aemet-last-valid"],name:`AEMET ${code} last valid`})}catch(error){console.warn(`[AEMET] ${code}: Runtime Cache no disponible; fallback en memoria`,error instanceof Error?error.message:"error desconocido")}}
async function readLastValid(code:string){try{const value=await getCache({namespace:"playa-hoy-aemet"}).get(lastValidKey(code));if(isWeatherResult(value))return value}catch(error){console.warn(`[AEMET] ${code}: no se pudo leer Runtime Cache`,error instanceof Error?error.message:"error desconocido")}return memoryLastValid.get(code)}
async function loadWeatherLive(municipality:string,code:string):Promise<WeatherResult>{const apiKey=process.env.AEMET_API_KEY;if(!apiKey)throw new Error("AEMET_API_KEY configured: false");const endpoint=`${API_BASE}/prediccion/especifica/municipio/horaria/${code}?api_key=${encodeURIComponent(apiKey)}`;const metadataResponse=await fetchWithRetry(endpoint,"fase metadata");if(!metadataResponse.ok)throw new Error(`fase metadata · HTTP ${metadataResponse.status}`);const metadata=await metadataResponse.json() as MetadataResponse;if(!metadata.datos)throw new Error(`fase metadata · respuesta sin URL datos${metadata.estado?` · estado ${metadata.estado}`:""}`);const dataResponse=await fetchWithRetry(metadata.datos,"fase datos");if(!dataResponse.ok)throw new Error(`fase datos · HTTP ${dataResponse.status}`);const result=parseWeather(await dataResponse.json() as AemetPayload[]);await persistLastValid(code,result);console.info(`[AEMET] ${municipality}: OK`);return result}
const getCachedWeather=unstable_cache(loadWeather,["aemet-municipal-hourly-v5"],{revalidate:AEMET_CACHE_SECONDS,tags:["aemet-weather"]});const inFlight=new Map<string,Promise<WeatherResult|null>>();let requestQueue:Promise<unknown>=Promise.resolve();function schedule<T>(task:()=>Promise<T>){const run=requestQueue.then(task,task);requestQueue=run.then(()=>wait(AEMET_REQUEST_SPACING_MS),()=>wait(AEMET_REQUEST_SPACING_MS));return run}
async function loadWeather(municipality:string,code:string){return schedule(()=>loadWeatherLive(municipality,code))}
export async function getWeather(municipality:string):Promise<WeatherResult|null>{const apiKeyConfigured=Boolean(process.env.AEMET_API_KEY);const code=AEMET_MUNICIPALITY_CODES[municipality];if(!apiKeyConfigured){console.error(`[AEMET] ${municipality}: ERROR AEMET_API_KEY configured: false`);return null}if(!code){console.error(`[AEMET] ${municipality}: ERROR municipio sin código AEMET`);return null}const pending=inFlight.get(code);if(pending)return pending;const request=getCachedWeather(municipality,code).catch(async error=>{const message=error instanceof Error?error.message:"desconocido";const stale=await readLastValid(code);if(stale){console.warn(`[AEMET] ${municipality}: usando último dato válido por fallo: ${message}`);return{...stale,stale:true}}console.error(`[AEMET] ${municipality}: ERROR ${message}`);return null}).finally(()=>inFlight.delete(code));inFlight.set(code,request);return request}
